src/main/java/kr/co/teacherforboss/domain/EmailAuth.java
src/main/java/kr/co/teacherforboss/domain/enums/Purpose.java

close #10 
- EmailAuth 엔티티 추가
- Purpose enum 추가
Purpose enum의 경우 임의로 SIGNUP, ID, PW로 두었는데 추후에 기능에 따라 추가하거나 수정하면 될 거 같습니당

:sparkles: [FEAT] EmailAuth 엔티티 추가

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/apiPayload/exception/handler/MemberHandler.java
src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
src/main/java/kr/co/teacherforboss/domain/Member.java
src/main/java/kr/co/teacherforboss/domain/PhoneAuth.java
src/main/java/kr/co/teacherforboss/repository/EmailAuthRepository.java
src/main/java/kr/co/teacherforboss/repository/MemberRepository.java
src/main/java/kr/co/teacherforboss/repository/PhoneAuthRepository.java
src/main/java/kr/co/teacherforboss/service/AuthService/AuthCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
src/test/java/kr/co/teacherforboss/service/AuthService/AuthCommandServiceImplTest.java

close #21 
- PhoneAuth 엔티티 추가
- Member 엔티티 phone 컬럼 추가
- 회원가입 API 로직 수정
- member 중복 여부 확인 추가
- EmailAuth isChecked 조건 체크 추가
- PhoneAuth isChecked 조건 체크 추가
>
> 회원가입 API 테스트 성공 부분의 경우 비밀번호 암호화 관련하여 generateSalt(), generateHash() 메서드를 사용해야하는데요!  Spring의 ReflectionTestUtils를 사용할지 고민했는데, private 메서드 자체를 테스트한다면 테스트 코드와의 결합력이 높아지기도 하고 테스트 코드 사용 비용이 높아지니 최대한 지양하려고 하다.. 우선 객체의 비밀번호(salt, hash)값을 임의로 설정한 후 저장된 후의 이메일, 이름값만 비교해서 return하는 식으로 추가했는데요! 혹시 더 좋은 방법이 있을까요....?!

✨[FEAT] Member 엔티티 phone 컬럼 추가 & 회원가입 API 로직 수정

---

src/main/java/kr/co/teacherforboss/config/jwt/JwtTokenProvider.java
src/main/java/kr/co/teacherforboss/config/jwt/filter/JwtAuthenticationFilter.java
src/main/java/kr/co/teacherforboss/web/controller/AuthController.java

close #48 
- JWT 전달 과정에서 'Bearer ' 문자열 처리
- **Postman에서 테스트 하는 경우, Header에 따로 명시하지 않고 Auth에서 Bearer Token에 AcessToken값 입력해주시면 됩니다!**
- 로그아웃시, Header의 accessToken에 Beaer 문자열이 존재하지 않는 경우 예외처리
- JwtAuthenticationFilter에서 Bearer 문자열 존재 여부 예외처리
>
**사전 정보 저장 (/api/v1/members/survey) API에서 JWT 인증 테스트 완료**
- Auth에 토큰을 입력한 경우 (사용자 인증 성공)
- Auth에 토큰을 입력하지 않은 경우 (존재하지 않는 사용자 예외처리 응답)

🐛[FIX] JWT 토큰 파싱 로직 수정 (Bearer 누락)

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
src/main/java/kr/co/teacherforboss/domain/mapping/AgreementTerm.java
src/main/java/kr/co/teacherforboss/repository/AgreementTermRepository.java
src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/validation/annotation/CheckTrueOrFalse.java
src/main/java/kr/co/teacherforboss/validation/validator/CheckTrueOrFalseValidator.java
src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java

close #51 
- AgreementTerm 엔티티 추가 & @CheckTrueOrFalse 어노테이션 추가 (T, F 값 검증)
- 회원가입 request body 필드 추가
- 수신 동의 테이블 추가에 따른 회원가입 로직 수정
- 회원가입시 필요한 필수 약관동의 모두 T가 아닐시 에러
- 약관동의 관련 필드 모두 T나 F값이 아니면 에러
>
> 아놔 생성된 파일 먼저 커밋하니까 나머지 파일들도 올라가버려서 커밋 메세지가.. 저리 단조롭게 엔티티 추가 & 어노테이션 생성으로 마무리 되었네요 회원가입 로직 수정도 추가입니당!

✨[FEAT] 회원가입 Request body 필드 추가

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
src/main/java/kr/co/teacherforboss/domain/Member.java
src/main/java/kr/co/teacherforboss/domain/enums/LoginType.java
src/main/java/kr/co/teacherforboss/repository/MemberRepository.java
src/main/java/kr/co/teacherforboss/service/authService/AuthCommandService.java
src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/util/PasswordUtil.java
src/main/java/kr/co/teacherforboss/validation/annotation/CheckSocialType.java
src/main/java/kr/co/teacherforboss/validation/validator/CheckSocialTypeValidator.java
src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java

close #41 
- 네이버, 카카오의 경우 소셜 로그인 진행시 비밀번호를 한번 입력 받기에 password 필드 추가했습니다!
- 소셜 로그인시 email이 필수로 필요하고, 새로 소셜 회원가입을 진행한다면 추가로 name, phone값이 필요하기에 (socialType은 늘 필수, 그 외 값들은 선택) name, phone null값 검증은 서비스단에서 진행했습니다~!
- ResetPasswordDTO 리팩토링 진행
- 소셜 로그인시 프론트에서 비밀번호를 가져올 수 없기에 자바의 SecureRandom을 사용하여 비밀번호 저장
**소셜 로그인 로직**
1. 일반 회원가입으로 등록된 계정인지 확인
2. 소셜 로그인으로 이미 등록된 계정인지 확인
- 등록되어 있다면 바로 로그인 
- 등록되지 않았다면 회원가입 진행
- LoginType kakao(2), naver(3)에 해당하지 않는 int값일 경우 예외 처리 커스텀 어노테이션 추가
- kakao, naver를 제외한 로그인 유형으로 가입한 이메일인 경우 예외처리
- Social 타입으로 회원가입 진행시 name, phone 필수로 기입했는지 여부 확인
>
> 임시 비밀번호 사이즈를 8로 우선 설정했는데요! (사유: 일반 회원가입시 최소 길이가 8) 이 길이라면 괜찮을까요?

✨[FEAT] 소셜로그인 API

---

src/main/java/kr/co/teacherforboss/apiPayload/ApiResponse.java
src/main/java/kr/co/teacherforboss/apiPayload/exception/ExceptionAdvice.java

close #70 
@Valid 어노테이션에서 실패 시 던지는 Exception의 Response 구조 변경했습니다.
- AS-IS
- TO-BE
>

♻️[REFACTOR] @Valid Exception Response 구조 변경

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/apiPayload/exception/handler/ExamHandler.java
src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
src/main/java/kr/co/teacherforboss/domain/AgreementTerm.java
src/main/java/kr/co/teacherforboss/domain/Exam.java
src/main/java/kr/co/teacherforboss/domain/ExamCategory.java
src/main/java/kr/co/teacherforboss/domain/MemberAnswer.java
src/main/java/kr/co/teacherforboss/domain/MemberExam.java
src/main/java/kr/co/teacherforboss/domain/Question.java
src/main/java/kr/co/teacherforboss/domain/QuestionChoice.java
src/main/java/kr/co/teacherforboss/domain/enums/ExamType.java
src/main/java/kr/co/teacherforboss/repository/AgreementTermRepository.java
src/main/java/kr/co/teacherforboss/repository/ExamRepository.java
src/main/java/kr/co/teacherforboss/repository/MemberAnswerRepository.java
src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java
src/main/java/kr/co/teacherforboss/repository/QuestionChoiceRepository.java
src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/service/examService/ExamCommandService.java
src/main/java/kr/co/teacherforboss/service/examService/ExamCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
src/main/java/kr/co/teacherforboss/web/dto/ExamRequestDTO.java
src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
src/test/java/kr/co/teacherforboss/repository/questionRepository/QuestionRepositoryTest.java
src/test/java/kr/co/teacherforboss/util/ExamTestUtil.java

close #77 
- 초기 입력받은 검증된 Member 객체와 examId로 MemberExam 객체 생성
- body로 입력받은 questionAnsList의 questionId (question), questionOptionId (questionChoice)로 DB에 존재하는지 검증 후 답이 맞을 시 score 점수 추가 (lambda 동시성 이슈로 score를 AtomicInteger type으로 선언)
- question, questionChoice로 MemberAnswer 객체 생성하여 람다식으로 리스트로 묶어냄 (-> MemberAnsList)
- MemberAnsList 리스트 객체에 MemberExam 객체 할당한 후  DB에 모두 저장
- 마찬가지로 score 값 저장한 MemberExam 객체 또한 DB에 저장
- 시험 Id, 문제 Id, 선지 Id가 존재하지 않는 경우 예외 처리
- 시험 중복 제출 예외 처리
- 모든 시험 문제에 대해 선지 선택 안할 시 예외 처리
- 엔티티 컬럼 사이즈 괜찮을까요?
- 서비스 로직 이상하거나 좀 더 수정하고 싶은 부분 있다면 알려주세요! 테스트 코드도 이어서 올리겠습니당
- 프론트에서 API 개수 리소스 차이 때문에 body값을 Id보다 String으로 전달하는게 좋다고 하셔서 우선 선지 부분만 String으로 받도록 하였습니다!

✨[FEAT] 시험 보기 API 

---

src/main/java/kr/co/teacherforboss/config/RedisConfig.java

close #106 
- Redis Config 추가
- Redis Config 를 별도로 추가하지 않더라도, Spring Boot에서 자동으로 구성을 설정해줌
- 자동 구성 vs 별도 Redis Config
- 자동 구성 시 기본적으로 JdkSerializationRedisSerializer를 사용하여 키와 값을 직렬화
-> Java 객체를 Redis에 저장하고 검색할 때 유용하지만, 저장된 데이터를 Redis CLI 등으로 직접 조회했을 때 가독성이 떨어지는 단점
- 작성한 Redis Config 에서는 StringRedisSerializer를 사용
-> Redis에 저장된 데이터를 더 쉽게 읽고 이해할 수 있으며, 이는 특히 문자열 데이터를 주로 다루는 경우에 유용
=> 우리는 문자열 데이터(refresh token)를 주로 다루기 때문에 커스텀한 config가 더 유용할 것이라 판단함
+) 또한 잘 저장되었는지 확인하기 위해 redis CLI를 할 때에서 보기 편할 것이라 생각함
>

✨[FEAT] RedisConfig 파일 추가

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
src/main/java/kr/co/teacherforboss/domain/MemberAnswer.java
src/main/java/kr/co/teacherforboss/domain/MemberExam.java
src/main/java/kr/co/teacherforboss/domain/QuestionChoice.java
src/main/java/kr/co/teacherforboss/repository/QuestionChoiceRepository.java
src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
src/main/java/kr/co/teacherforboss/service/examService/ExamCommandService.java
src/main/java/kr/co/teacherforboss/service/examService/ExamCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
src/main/java/kr/co/teacherforboss/web/dto/ExamRequestDTO.java
src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java

close #103 
- MemberExam에 time(걸린 시간) 컬럼 추가
- 시험 보기 리팩토링
- 기존에 사용했던 setScore()와 setMemberExam()은 추후 변경될 일이 없음에도 변경 가능성을 열어두는 것이기 때문에 해당 세터 메서드를 사용하지 않도록 수정함
- 수정된 코드에서 처음에 한 번 repository에서 조회해서 Map에 Question과 QuestionChoice를 저장해두는 방식을 사용함.
- Question과 QuestionChoice를 repository에서 조회하는 코드가 2번씩 반복되게 짤 수도 있지만, 동일한 세션임에도 1차 캐시를 사용하는지 확실하게 여부를 확인할 수 없었음 (커맨드 로그에는 쿼리가 중복으로 호출되는 것처럼 보임)
>
시험 보기 서비스 부분 봐주세요.. 😭
총 3번 리팩토링 했는데..
1. setter 제거, repository에서 Question 및 QuestionChoice 중복 조회 발생
2. 처음에 Map을 만들어 repository에서 Question과 QuestionChocie를 한 번만 조회하고 뒤에서는 Map에서 조회하도록 수정
Question과 QuestionChoice를 Map에서 조회하는 과정에서 null 체크 후 …

✨[FEAT] MemberExam에 time 컬럼 추가 및 시험 보기 리팩토링

---

src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java
src/main/java/kr/co/teacherforboss/service/examService/ExamCommandService.java
src/main/java/kr/co/teacherforboss/service/examService/ExamCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java

close #117 
- 재시험 보기 가능에 따라 시험 결과 조회시 최신순 정렬되어 top 1만 조회할 수 있도록 repository 메서드 수정
- 재시험 보기 가능에 따라 시험 저장 API response 값 변경
- 오답노트 조회 API path variable memberExamId로 수정
- 오답노트 조회 API response 값에 questionId 추가
>

✨[FEAT] 오답노트 리스트 response 데이터 추가

---

src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
src/main/java/kr/co/teacherforboss/repository/ExamRepository.java
src/main/java/kr/co/teacherforboss/service/examService/ExamQueryService.java
src/main/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImpl.java
src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java

close #128 
시험 치룬 횟수 조회하는 API 구현했습니다.
추후에 마이페이지 같은 곳에서 내가 본 시험 목록을 조회할 수도 있을 것같아 Exam list를 반환하는 서비스 함수로 작성하였습니다.
>

✨[FEAT] 시험 치룬 횟수 조회 API

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/config/ExamConfig.java
src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
src/main/java/kr/co/teacherforboss/domain/enums/ExamQuarter.java
src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java
src/main/java/kr/co/teacherforboss/service/examService/ExamQueryService.java
src/main/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImpl.java
src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java

close #123 
- 네이티브 쿼리로 사용자 점수 평균 쿼리문, 같은 업종 사장님 점수 평균 쿼리문 작성
>
- 네이티브 쿼리로 round까지 점수 평균값 구하게 할지, 혹은 조건에 따른 memberExam 리스트만 조회한 뒤 평균을 구할지 고민입니다! 후자 고민하는 이유는 추후 repository 메서드문 재활용할 수 있을 거 같아서요..! 아예 지금처럼 쿼리문에서 평균 내버리는 게 날 거 같아 우선 네이티브 쿼리 작성했습니당

✨[FEAT] 같은 업종 사장님들 점수 API

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
src/main/java/kr/co/teacherforboss/domain/Exam.java
src/main/java/kr/co/teacherforboss/domain/ExamCategory.java
src/main/java/kr/co/teacherforboss/domain/ExamSubCategory.java
src/main/java/kr/co/teacherforboss/domain/Tag.java
src/main/java/kr/co/teacherforboss/repository/ExamCategoryRepository.java
src/main/java/kr/co/teacherforboss/repository/TagRepository.java
src/main/java/kr/co/teacherforboss/service/examService/ExamQueryService.java
src/main/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImpl.java
src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java

close #125 
시험 태그 (= 시험 세부 카테고리) 리스트 조회
**Postman 테스트**
일단 uri가 exams/category/tags 라서 
따로 category값을 PathVariable로 설정하진 않았는데,
지금 구현한 방식으로 전체 category의 tag값을 조회하도록 하면 될까요?
그러니까,
1) exams/{categoryId}/tags 로 해서 각 카테고리 마다 tag 리스트를 조회하게 할지
2) exams/category/tags로 하고 그냥 전체 카테고리와 해당 카테고리의 tag 리스트를 조회하게 할지
위 두 방식 중에 우선은 2번처럼 구현을 한 상태인데, 1번처럼 하지 않는게 맞나요?!
(저는 피그마에서 각 카테고리 별로 보여야 하는 tag가 다르니까.. 1번 방식처럼 구현하는게 프론트 입장에선 더 편하지 않을까 생각하긴 했는데, 두 방식 중 어떤식으로 구현해야 좋을지..! 여러분들 의견이 궁금합니댜)

✨[FEAT] 시험 태그 리스트 조회 API

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/config/ExamConfig.java
src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
src/main/java/kr/co/teacherforboss/repository/ExamRepository.java
src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java
src/main/java/kr/co/teacherforboss/repository/TagRepository.java
src/main/java/kr/co/teacherforboss/service/examService/ExamQueryService.java
src/main/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImpl.java
src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java

close #132 
**시험 리스트 조회 API 구현**
* 시험명
* 시험 세부 설명
* 시험 태그
* 시험 카테고리
* 시험 응시여부
* 시험 오답률
* 시험 점수
* 시험 PASS/FAIL 여부
멤버 토큰이 유효하지 않을 경우, 오류 메시지 반환

✨[FEAT] 시험 리스트 조회 API

---

src/main/java/kr/co/teacherforboss/domain/Member.java
src/main/java/kr/co/teacherforboss/repository/ExamRepository.java
src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java
src/test/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImplTest.java
src/test/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImplTest.java
src/test/java/kr/co/teacherforboss/service/memberService/MemberQueryServiceImplTest.java
src/test/java/kr/co/teacherforboss/util/AuthTestUtil.java
src/test/java/kr/co/teacherforboss/util/ExamTestUtil.java

close #137 
- Jmeter와 Junit을 활용하여 평균 점수 조회 쿼리 성능 개선을 위한 리팩토링을 진행했습니다.
- 로컬 DB에 약 5천 건의 데이터를 삽입해 API 부하 테스트를 진행했습니다.
1. MemberExam 리스트로 반환 -> 이전에 민지님과 PR 코멘트로 재사용 가능성에 대해 고민하며 추후 성능 테스트를 통해 해당 부분을 적용할지 이야기를 나눴었는데, 실제 테스트 결과 적은 더미 데이터만으로도 성능이 떨어져서 패스했습니다.. ㅎ
2. 쿼리 힌트 적용 -> 약 200ms 가량 감소하여 적용
3. BETWEEN 대신 부등호 조건 -> 검색 시작점이 달라져 약 100-200ms이 더 줄어들었습니다
4. 부정형 조건 대신 left outer join -> 부정형 조건을 적용하는 경우 부정형 조건 그 외의 범위를 다 탐색하기에, join을 통해 null 값을 찾는 쿼리로 수정한 후 테스트를 해봤습니다. 이론과는 다르게 약 N배 가량 시간이 지연되어 이 부분은 패스....
블로그에 기록하며 작성했는데 혹시 궁금하시다면 코멘트로 달아두겠습니다!
테스트 코드도 간단하게 작성해서 로직 비교해가며 실행했습니다 !
>

♻️ [REFACTOR] 같은 업종 사장님 평균 점수 조회 API 쿼리 리팩토링 & 동시성 테스트

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
src/main/java/kr/co/teacherforboss/domain/Member.java
src/main/java/kr/co/teacherforboss/domain/TeacherInfo.java
src/main/java/kr/co/teacherforboss/domain/enums/Gender.java
src/main/java/kr/co/teacherforboss/domain/enums/Level.java
src/main/java/kr/co/teacherforboss/domain/enums/Role.java
src/main/java/kr/co/teacherforboss/repository/MemberRepository.java
src/main/java/kr/co/teacherforboss/repository/TeacherInfoRepository.java
src/main/java/kr/co/teacherforboss/service/authService/AuthCommandService.java
src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/service/authService/AuthQueryService.java
src/main/java/kr/co/teacherforboss/service/authService/AuthQueryServiceImpl.java
src/main/java/kr/co/teacherforboss/util/PasswordUtil.java
src/main/java/kr/co/teacherforboss/validation/annotation/CheckRole.java
src/main/java/kr/co/teacherforboss/validation/validator/CheckRoleValidator.java
src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
src/main/java/kr/co/teacherforboss/web/dto/AuthResponseDTO.java
src/test/java/kr/co/teacherforboss/util/AuthTestUtil.java

close #142 
- Member 엔티티 nickname 필드 추가
- TeacherInfo 엔티티 생성
- 사용자 역할 생성에 따라 Role Enum 수정 (BOSS:1/TEACHER:2/ADMIN)
- 티쳐 레벨 관리하는 Level Enum 생성
- 닉네임 중복 검증 API 추가 (AuthQueryService)
- 회원가입, 소셜로그인 로직 추가 (AuthCommandService)
- 회원가입, 소셜로그인의 공통되는 필드 묶어서 JoinCommonDTO 추상 클래스 생성 후 각각 상속받는 JoinDTO와 SocialLoginDTO로 수정
- RequestBody로 전달되는 Role 값을 검증하는 커스텀 어노테이션 CheckRole 생성
일반 회원가입 로직 (_**보스/티쳐선택** -> 기존 회원가입 -> **새로 추가된 프로필 설정 부분 후 찐 가입 완료!!**_) 로직과 소셜로그인 로직 (_기존 소셜로그인 -> **보스/티쳐 선택** -> **새로 추가된 프로필 설정 부분 후 찐 가입 완료!!**_) 흐름에 따라 코드 추가했습니당. 
두 기능 모두 공통되는 부분이 볼드체 처리한 부분인데, 보스/티쳐 선택의 경우 DTO에 커스텀 어노테이션 CheckRole로 검증했고, 새로 추가된 프로필 설정에 경우 보스와 티쳐의 따라 케이스가 다르기에 따로 메서드 분기 처리했습니다! 
**😶‍🌫️로직을 구현하며 써내려간 고민의 흔적들 ... (귀찮으면 안읽어도 됨)**
1. 처음엔 이렇게 role 타입에 따라 boss, teacher 나눠서 …

✨[FEAT] 티쳐/보스 구분에 따른 회원가입/소셜로그인 API 로직 추가 & 닉네임 중복 검사 API

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
src/main/java/kr/co/teacherforboss/domain/TeacherInfo.java
src/main/java/kr/co/teacherforboss/util/AES256Util.java
src/test/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImplTest.java
src/test/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImplTest.java
src/test/java/kr/co/teacherforboss/service/memberService/MemberQueryServiceImplTest.java
src/test/java/kr/co/teacherforboss/util/AuthTestUtil.java
src/test/java/kr/co/teacherforboss/util/ExamTestUtil.java

close #151
AES256 암호화 유틸 만들고, 계좌번호 암호화해서 저장하도록 수정했습니다.
암호화 시 return값이 32자리이므로 티쳐인포 엔티티의 계좌번호 컬럼도 32자리로 수정했습니다.
그리고 변수명 변경하고나서 기존 테스트코드가 안돌아가길래 안돌아가는 부분만 수정했습니다.
주석처리도 했는데, 이건 나중에 담당자분이 다시 테스트코드 작성해주면 될 것 같습니다.
암호화 과정에서 오류가 났을 때, 별도의 에러를 던지도록 했습니다.
>

[FEAT] AES256 암호화

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/apiPayload/exception/handler/BoardHandler.java
src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
src/main/java/kr/co/teacherforboss/domain/Hashtag.java
src/main/java/kr/co/teacherforboss/domain/Post.java
src/main/java/kr/co/teacherforboss/domain/PostBookmark.java
src/main/java/kr/co/teacherforboss/domain/PostHashtag.java
src/main/java/kr/co/teacherforboss/domain/PostLike.java
src/main/java/kr/co/teacherforboss/repository/HashtagRepository.java
src/main/java/kr/co/teacherforboss/repository/PostBookmarkRepository.java
src/main/java/kr/co/teacherforboss/repository/PostHashtagRepository.java
src/main/java/kr/co/teacherforboss/repository/PostLikeRepository.java
src/main/java/kr/co/teacherforboss/repository/PostRepository.java
src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryService.java
src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java
src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
src/main/java/kr/co/teacherforboss/web/dto/BoardRequestDTO.java
src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java

close #155 
**보스톡 게시물 작성**
**보스톡 게시물 상세 조회**
- Hashtag, Post, PostBookmark, PostHashtag, PostLike 엔티티 추가
- 보스톡 게시물 작성 API 제작
- 보스톡 게시물 상세 조회 API 제작
**보스톡 게시물 작성**
- requestBody valid 진행
**보스톡 게시물 상세 조회**
- postId 값에 따라 게시물 존재 여부 검증
>
- imageUrl 컬럼 크기 정해야하는데 우선 임시로 정해두지 않았습니다
- 유저가 해시태그 리스트 입력 중 중복된 값들을 (ex "해시태그1", "해시태그1") 입력할 때 예외 검증 필요할까요?
- **보스톡 게시물 작성 API에서 동시성 제어가 필요한 부분이 있습니다. (꼭 봐주세요! 🤧)** 
예를들어, 
(해시태그 'a'는 데이터베이스에 없던 태그)
1. 유저 1이 해시태그 'a' 먼저 생성
2. 유저 2이 해시태그 'a' 생성
3. 유저 2가 게시물 먼저 작성 완료
4. 그 다음으로 유저 1이 게시물 작성 완료
1, 2번에서 해시태그 'a'를 생성하게 되는데, 3번 과정 진행되면 유저 1은 해시태그 생성 구문을 멈추고 조회로 돌아가야 합니다. 
해시태그 테이블에서 중복된 해시태그를 …

✨[FEAT] 보스톡 게시글 작성/상세 조회

---

src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java

close #203 
티쳐로 회원가입시 입력받은 role 타입에 따라 teacherInfo를 save해야하는데, 티쳐가 아닌 보스 타입일 때 해당 로직을 수행하도록 코드를 설정했었습니다. 보스에서 티쳐로 수정했습니다!
>

🐛[FIX] 회원가입 Role 선택 오타 수정

---

src/main/java/kr/co/teacherforboss/repository/EmailAuthRepository.java
src/main/java/kr/co/teacherforboss/repository/PhoneAuthRepository.java
src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java

close #207 
dev 서버에서 회원가입시 400 에러가 발생하여, 비즈니스 로직에서 조건 검증하는 부분의 파라미터 타입과 DTO size 설정을 변경하였습니다.
>

❤️‍🩹 [FIX] 회원가입 400 에러 수정

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
src/main/java/kr/co/teacherforboss/domain/Answer.java
src/main/java/kr/co/teacherforboss/domain/Question.java
src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
src/main/java/kr/co/teacherforboss/web/dto/BoardRequestDTO.java
src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java

close #169
- 답변 작성 API 구현
- request에 timestamp nullable하게 수정 & 서비스단에서 imageCount>0&&timestamp==null인 경우 에러 처리 (질문 작성, 답변 작성)
- Question 엔티티에 imageTimestamp @Notnull 제거
- 보스톡 게시글 좋아요 & 북마크 URI /board/board로 되어있는거 수정
>

✨[FEAT] 티쳐톡 답변 작성 API

---

src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
src/main/java/kr/co/teacherforboss/converter/StringConverter.java
src/main/java/kr/co/teacherforboss/domain/Answer.java
src/main/java/kr/co/teacherforboss/domain/Post.java
src/main/java/kr/co/teacherforboss/domain/Question.java
src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/service/s3Service/S3QueryService.java
src/main/java/kr/co/teacherforboss/service/s3Service/S3QueryServiceImpl.java
src/main/java/kr/co/teacherforboss/validation/annotation/CheckImageOrigin.java
src/main/java/kr/co/teacherforboss/validation/annotation/CheckImageUuid.java
src/main/java/kr/co/teacherforboss/validation/validator/CheckImageOriginValidator.java
src/main/java/kr/co/teacherforboss/validation/validator/CheckImageUuidValidator.java
src/main/java/kr/co/teacherforboss/validation/validator/CheckPurposeValidator.java
src/main/java/kr/co/teacherforboss/web/controller/S3Controller.java
src/main/java/kr/co/teacherforboss/web/dto/BoardRequestDTO.java

close #215 
이미지 저장 방식 수정했습니다. -> imageUuid & imageIndex(; delimeter)로
- Post, Question, Answer 엔티티에 imageUuid & imageIndex 칼럼으로 변경
- savePost, saveQuestion, editQuestion, saveAnswer에서 이미지 저장 로직 수정
- req body에 imageUrlList - null, 빈 배열, size=1, size=3 테스트 완료
>

✨[FEAT] 이미지 저장 방식 수정

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
src/main/java/kr/co/teacherforboss/domain/Answer.java
src/main/java/kr/co/teacherforboss/domain/common/BaseEntity.java
src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
src/main/java/kr/co/teacherforboss/web/dto/BoardRequestDTO.java
src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java

close #217 
티쳐톡 답변 수정 API 구현했습니다.
+
티쳐톡 질문 수정 API response에 updatedAt이어야 하는데 createdAt으로 되어있길래 이것도 수정했습니다
base entity softdelete에서 예외 던지는거 삭제했습니다 (삭제된 댓글이 존재하는 경우 게시글 삭제 시 모든 댓글을 지울 때 오류가 나서..)
>

✨[FEAT] 티쳐톡 답변 수정 API

---

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
src/main/java/kr/co/teacherforboss/apiPayload/exception/handler/PaymentHandler.java
src/main/java/kr/co/teacherforboss/converter/PaymentConverter.java
src/main/java/kr/co/teacherforboss/domain/Exchange.java
src/main/java/kr/co/teacherforboss/domain/TeacherSelectInfo.java
src/main/java/kr/co/teacherforboss/domain/enums/ExchangeType.java
src/main/java/kr/co/teacherforboss/domain/vo/mailVO/ExchangeMail.java
src/main/java/kr/co/teacherforboss/repository/ExchangeRepository.java
src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandService.java
src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/validation/annotation/CheckTrueOrFalse.java
src/main/java/kr/co/teacherforboss/validation/annotation/DivisibleBy.java
src/main/java/kr/co/teacherforboss/validation/validator/DivisibleByValidator.java
src/main/java/kr/co/teacherforboss/web/controller/PaymentController.java
src/main/java/kr/co/teacherforboss/web/dto/PaymentRequestDTO.java
src/main/java/kr/co/teacherforboss/web/dto/PaymentResponseDTO.java
src/main/resources/templates/exchange.html

close #274 
- Exchange 엔티티 추가
- TeacherSelectInfo 엔티티 필드명 수정 (point -> points)
- API 호출시 이메일 전송과 함께 보유 포인트 감소
- 550TP 미만 보유시 예외 처리
- 보유 TP보다 더 높은 TP 입력시 예외 처리
- 100TP 단위로 떨어지는 포인트 입력하지 않았을시 예외 처리
>
이메일 전송 -> 포인트 감소 -> Exchange 테이블 업데이트 순으로 로직 구성되는데 괜찮을까요?
그리고 새로운 아이콘 이미지 .. aws에 올라가 있나요??? 그거 받아서 이메일 화면에 보이는 이미지 변경하면 좋을 거 같아요 ㅎㅎ

✨[FEAT] 티포 환전 신청 API

---

src/main/java/kr/co/teacherforboss/converter/BoardConverter.java

close #301 
커뮤니티 게시글에서 탈퇴한 회원이 작성한 게시물/댓글의 경우 프로필 이미지 null, 닉네임 알 수 없음 처리 진행했습니다
티쳐톡 게시물 예시입니다 ~~ (id = 140)
>

✨[FEAT] 탈퇴한 회원 프로필 조회시 알 수 없음 처리

---

src/main/java/kr/co/teacherforboss/repository/PostRepository.java
src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java

close #222 
기존 쿼리에서 CONCAT 사용해서 비교군 + id 값으로 값들을 정렬하여 조회할 수 있도록 수정하였습니당
Jmeter로 부하 테스트시 속도도 빨라졌어용 굿
아래에 보스톡 좋아요 순으로 정렬했을 때 조회 속도 스크린샷입니다
>

♻️[REFACTOR] 보스톡/티쳐톡 게시글 무한스크롤 리팩토링

---

src/main/java/kr/co/teacherforboss/TeacherforbossApplication.java
src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
src/main/java/kr/co/teacherforboss/domain/Answer.java
src/main/java/kr/co/teacherforboss/domain/AnswerLike.java
src/main/java/kr/co/teacherforboss/domain/Question.java
src/main/java/kr/co/teacherforboss/domain/QuestionBookmark.java
src/main/java/kr/co/teacherforboss/domain/QuestionHashtag.java
src/main/java/kr/co/teacherforboss/domain/QuestionLike.java
src/main/java/kr/co/teacherforboss/domain/TeacherSelectInfo.java
src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
src/main/java/kr/co/teacherforboss/scheduler/QuestionScheduler.java
src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java

close #314 
- 채택 시 우선 채택만 되고 TP 지급 안함
- TP 지급 로직은 만들어놓되 주석처리 (스케줄러 돌리기 (매일 자정))
- 답변이 달린 시점부터 일주일간 채택되지 않을 시 자동 채택 (연장 시스템 삭제 & 스케줄러 돌리기 (매일 자정))
- 채택 하는 기준은 위 사진 -> 맞춰서 쿼리 작성
- teacher 가입할 때 teacherSelectInfo 생성
- Question 연관관계에 있는 엔티티에 `on delete cascade` 설정 (QuestionBookmark, QuestionHashtag, QuestionLike, Answer)
- Answer 연관관계에 있는 엔티티에 `on delete cascade` 설정 (AnswerLike)
- 스케줄러 돌리는 부분에 알림 TODO 적어뒀습니다
- 스케줄러 돌리는 코드에 답변 채택되는 경우 티쳐 정보 조회하는데 티쳐 status INACTIVE인 경우 롤백되더라구요.. 그래서 그 해당 답변 상태 INACTIVE로 해뒀고, 티쳐 회원탈퇴할 때 답변 상태 변경하는 거 (삭제하거나 INACTIVE로 바꾸거나 ) 이 부분은 나중에 자세히 보려고 TODO 작성해뒀습니다

✨[FEAT] 채택 플로우 수정

---

src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java

close #325 
- 회원가입시 사업자 인증 주석 처리
- 주석 처리했을 때 리턴값 명세서 추가
- DB에는 TeacherInfo의 `businessNumber` NotNull 아니어서 엔티티 @NotNull 안지웠어요
>

✨[FEAT] 회원가입시 사업자 인증 주석 처리

---

src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java

close #332 
동일한 이메일로 새로 가입할 때 사용자 없다는 에러 발생
-> 사용자 조회시 (getMember) email + **status** 조건 추가
>

🐛[FIX] 프로필 조회 API 탈퇴한 계정으로 조회되는 거 수정
