src/main/java/kr/co/teacherforboss/domain/Member.java, src/main/java/kr/co/teacherforboss/domain/common/BaseEntity.java, src/main/java/kr/co/teacherforboss/domain/enums/Role.java
close #5 
- BaseEntity status 컬럼 추가
- Member phone 컬럼 삭제
- Role enum 중 USR -> USER로 수정
DB 한번씩 다시 초기화하고 다시 돌려주세용!!
=> ❤️‍🩹 [FIX] BaseEntity & Member 엔티티 수정

build.gradle, src/main/java/kr/co/teacherforboss/config/SecurityConfig.java, src/main/java/kr/co/teacherforboss/config/SwaggerConfig.java, src/main/java/kr/co/teacherforboss/web/controller/TempController.java
close #8
swagger 설정 완료했습니다!
프로젝트 실행 후 http://localhost:8080/swagger-ui/index.html#/ 로 접속하시면 아래 화면 볼 수 있습니다.
>
=> 🔧 [FEAT] Swagger config

src/main/java/kr/co/teacherforboss/domain/Member.java, src/main/java/kr/co/teacherforboss/domain/common/BaseEntity.java, src/main/java/kr/co/teacherforboss/domain/enums/Gender.java
close #12 
- Member 엔티티에 birthDate, gender 컬럼 추가
- Gender enum 추가
- BaseEntity의 Status 기본값 추가
>
=> ✨ [FEAT] Member 엔티티 컬럼 추가

build.gradle, src/main/java/kr/co/teacherforboss/apiPayload/ApiResponse.java, src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/apiPayload/exception/ExceptionAdvice.java, src/main/java/kr/co/teacherforboss/apiPayload/exception/handler/MailHandler.java, src/main/java/kr/co/teacherforboss/config/MailConfig.java, src/main/java/kr/co/teacherforboss/config/SecurityConfig.java, src/main/java/kr/co/teacherforboss/converter/AuthConverter.java, src/main/java/kr/co/teacherforboss/domain/EmailAuth.java, src/main/java/kr/co/teacherforboss/domain/Member.java, src/main/java/kr/co/teacherforboss/domain/common/BaseEntity.java, src/main/java/kr/co/teacherforboss/domain/enums/Purpose.java, src/main/java/kr/co/teacherforboss/domain/vo/mailVO/CodeMail.java, src/main/java/kr/co/teacherforboss/domain/vo/mailVO/Mail.java, src/main/java/kr/co/teacherforboss/repository/EmailAuthRepository.java, src/main/java/kr/co/teacherforboss/service/AuthService/AuthCommandService.java, src/main/java/kr/co/teacherforboss/service/AuthService/AuthCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/service/MailService/MailCommandService.java, src/main/java/kr/co/teacherforboss/service/MailService/MailCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/validation/annotation/CheckPurpose.java, src/main/java/kr/co/teacherforboss/validation/validator/CheckPurposeValidator.java, src/main/java/kr/co/teacherforboss/web/controller/AuthController.java, src/main/java/kr/co/teacherforboss/web/controller/TempController.java, src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java, src/main/java/kr/co/teacherforboss/web/dto/AuthResponseDTO.java, src/main/resources/templates/code.html, src/test/java/kr/co/teacherforboss/service/AuthService/AuthCommandServiceImplTest.java
close #13
이메일 인증 API 작업했습니다.
- Request Body의 email로 인증 코드를 포함한 메일을 전송합니다.
Request Body에 email 필드가 이메일 형식이 아닐 경우 400을 보냅니다!
테스트 코드 너무 어려워요😭
실패하는 테스트도 작성해야 하는데 마땅히 사례가 생각나지 않아서 혹시 부족한 부분 있다면 말씀해주세요!
API 통합 테스트도 진행하는게 좋을까요?? 🤔
=> ✨[FEAT] 이메일 인증 API

src/main/java/kr/co/teacherforboss/web/dto/MemberRequestDTO.java
=> ❤️‍🩹[FIX] 사전정보 저장 Request 저장

src/main/java/kr/co/teacherforboss/converter/MemberConverter.java, src/main/java/kr/co/teacherforboss/domain/MemberSurvey.java, src/main/java/kr/co/teacherforboss/domain/converter/SurveyListConverter.java, src/main/java/kr/co/teacherforboss/validation/annotation/CheckSurvey.java, src/main/java/kr/co/teacherforboss/validation/validator/AbstractCheckSurveyValidator.java, src/main/java/kr/co/teacherforboss/validation/validator/CheckSurveyValidatorForInteger.java, src/main/java/kr/co/teacherforboss/validation/validator/CheckSurveyValidatorForIntegerList.java, src/main/java/kr/co/teacherforboss/web/dto/MemberRequestDTO.java
close #52 
사전정보 2번 단일 Survey -> List<Survey> 로 수정했습니다.
>
=> ❤️‍🩹[FIX] 사전정보 2번 list로 수정

src/main/java/kr/co/teacherforboss/validation/validator/CheckSurveyValidatorForIntegerList.java, src/main/java/kr/co/teacherforboss/web/dto/MemberRequestDTO.java
=> 🩹 #55 Fix: 사전정보 저장 Request Validation 추가

src/main/java/kr/co/teacherforboss/config/jwt/filter/JwtExceptionFilter.java, src/main/java/kr/co/teacherforboss/domain/vo/smsVO/CodeSMS.java, src/main/java/kr/co/teacherforboss/util/SmsUtil.java
=> ❤️‍🩹 #57 Fix: 인증번호 5자리로 변경

src/main/java/kr/co/teacherforboss/config/jwt/filter/JwtExceptionFilter.java, src/main/java/kr/co/teacherforboss/util/SmsUtil.java
=> 🎨[STYLE] delete log

src/main/java/kr/co/teacherforboss/util/SmsUtil.java
=> ⏪ #57 Fix: rewind from number 변수이름

src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
=> 🩹 [FIX] 휴대폰 인증번호 확인 request validation 수정

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/config/jwt/filter/JwtAuthenticationFilter.java, src/main/java/kr/co/teacherforboss/config/jwt/filter/JwtExceptionFilter.java, src/main/java/kr/co/teacherforboss/service/authService/AuthQueryServiceImpl.java
close #59 
- JwtExceptionFilter 예외처리 추가
- AuthenticationFilter에서 발생하는 에러 로그 삭제
- 로그아웃 시, JWT에 해당하는 유저 이메일 로그 메시지 변경
- JwtExceptionFilter 예외처리 추가 (ex. 로그인 시 유효하지 않는 토큰을 추가하는 경우)
>
=> ♻️[REFACTOR] JWT 에러 로그 삭제

src/test/java/kr/co/teacherforboss/service/memberService/MemberQueryServiceImplTest.java
close #58 
- 유저 존재 여부에 따라 프로필 조회 성공, 실패 테스트 코드 작성
>
> 트러블 슈팅에 작성해두긴 했는데 verify로 행위검증을 하려고 하는데 argumentMatcher로 파라미터 작성시 null로 조회되고 raw data로 작성하면 성공하더라구요..! raw data로 작성하면 when, thenReturn에서 mock 객체로 행동 정의한 것과 동일해서 의미가 있는가 싶기도 하고.. 어렵네요
=> ✅ [TEST] 프로필 조회 API 테스트

src/test/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImplTest.java, src/test/java/kr/co/teacherforboss/util/AuthTestUtil.java
close #67 
- 비밀번호 찾기에 필요한 성공, 실패 케이스 테스트 코드입니다!
- 필요한 더미데이터 추가
- 이메일 찾기 테스트와 로직이 거의 비슷합니다
>
=> ✅ [TEST] 비밀번호 찾기 API 테스트

src/main/java/kr/co/teacherforboss/validation/validator/CheckTrueOrFalseValidator.java
close #72 
- requestbody에 약관동의 관련 필드가 비어있을 시 NPE가 발생하는 문제 해결
- Validator에 null, isEmpty 조건 추가
>
=> ❤️‍🩹[FIX] 회원가입 약관동의 NPE 해결

src/main/java/kr/co/teacherforboss/repository/MemberRepository.java, src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
close #83 
이미 가입한 이메일로 회원가입시 예외 처리
>
=> ❤️‍🩹[FIX] 회원가입 이메일 중복 오류 수정

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/repository/MemberRepository.java, src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
=> ✨[FEAT] 이메일 및 전화번호 인증 중복체크

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/converter/ExamConverter.java, src/main/java/kr/co/teacherforboss/repository/ExamRepository.java, src/main/java/kr/co/teacherforboss/repository/MemberAnswerRepository.java, src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java, src/main/java/kr/co/teacherforboss/service/examService/ExamCommandService.java, src/main/java/kr/co/teacherforboss/service/examService/ExamCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/ExamController.java, src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
close #81 
- 사용자가 치룬 시험의 문제들의 답과 문제의 정답 선지를 비교하여 정답 개수, 오답 개수 선정
- 총 시험 문제 개수, 점수 조회
- 유효하지 않은 시험 Id 입력시 예외 처리
- 존재하지 않은 MemberExam일 시 예외 처리
- 코멘트 단 부분 확인 부탁드립니당!!
=> ✨[FEAT] 시험 결과 조회 API

src/main/java/kr/co/teacherforboss/config/jwt/JwtTokenProvider.java, src/main/java/kr/co/teacherforboss/web/controller/AuthController.java, src/main/java/kr/co/teacherforboss/web/dto/AuthResponseDTO.java
close #96
- 로그인 response에 사용자 이름도 함께 반환
>
=> ✨ [FEAT] 로그인 API response 사용자 이름 추가

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/repository/MemberRepository.java, src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
close #85 
- 회원가입시 전화번호 중복 여부 확인 예외 추가
>
=> :sparkles: [FEAT] 회원가입 전화번호 중복 검증 추가

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/converter/ExamConverter.java, src/main/java/kr/co/teacherforboss/domain/Question.java, src/main/java/kr/co/teacherforboss/repository/MemberAnswerRepository.java, src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java, src/main/java/kr/co/teacherforboss/service/examService/ExamCommandService.java, src/main/java/kr/co/teacherforboss/service/examService/ExamCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/ExamController.java, src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
close #89 
close #98 
- 문제 순서 컬럼 추가
- MemberExam으로 MemberAnswer 내에서 question의 answer, questionChoice의 choice 같은지 여부 비교하는 jpql 작성
- ErrorStatus 코드 번호 누락 부분 수정
- memberId, examId로 MemberExam 조회 예외 처리
>
=> ✨[FEAT] 오답노트 리스트 조회 API

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/converter/ExamConverter.java, src/main/java/kr/co/teacherforboss/repository/ExamRepository.java, src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java, src/main/java/kr/co/teacherforboss/service/examService/ExamQueryService.java, src/main/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/ExamController.java, src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
close #90
response 예시
```json
{
"isSuccess": true,
"code": "COMMON200",
"message": "성공입니다.",
"result": {
"questionList": [
{
"questionId": 1,
"questionSequence": 1,
"questionName": "테스트 문항",
"choiceList": [
{
"choiceId": 1,
"choiceName": "1번 보기"
},
{
"choiceId": 2,
"choiceName": "2번 보기"
},
{
"choiceId": 3,
"choiceName": "3번 보기"
},
{
"choiceId": 4,
"choiceName": "4번 보기"
},
{
"choiceId": 5,
"choiceName": "5번 보기"
}
]
},
{
"questionId": 2,
"questionSequence": 2,
"questionName": "테스트 문항 2",
"choiceList": [
{
"choiceId": 6,
"choiceName": "1번 보기"
},
{
"choiceId": 7,
"choiceName": "2번 보기"
},
{
"choiceId": 8,
"choiceName": "3번 보기"
},
{
"choiceId": 9,
"choiceName": "4번 보기"
},
{
"choiceId": 10,
"choiceName": "5번 보기"
}
]
}
]
}
}
```
> 이번 PR에서 작업한 Exception 처리 …
=> ✨[FEAT] 시험 문항 리스트 조회 API

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/config/jwt/PrincipalDetails.java, src/main/java/kr/co/teacherforboss/repository/MemberRepository.java, src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/service/examService/ExamCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
close #101 
- 이름, 전화번호 null체크 DTO 단으로 수정
=> MEMBER4005에서 COMMON400으로 수정됨 
- request dto에서 이메일 valid message 추가
- 전화번호 중복 시 회원가입 안되도록 로직 추가
- .collect(Collectors.toList()) -> .toList()로 수정 (이유는 아래 자료 참고)
>
아래 댓글 확인
- .collect(Collectors.toList()) 
- java8부터 사용 가능
- 반환된 리스트는 변경 가능할 수 있음 
- .toList()
- java16부터 사용 가능한 Stream 인터페이스의 새로운 메소드
- 반화된 리스트는 불변리스트로, 리스트에 대한 변경 시도 (추가, 삭제, 요소 변경 등) 시 UnsupportedOperationException 발생
=> toList() 사용 시 코드를 더 간결하게 만들고, 불변리스트를 반환한다는 점을 명시적으로 나타냄.
따라서, 함수형 프로그래밍 패러다임과 불변성이 중요한 현대적 자바 애플리케이션 개발에 더 적합하다고 볼 수 있다.
=> 🐛[FIX] 소셜로그인 전화번호 중복 체크 추가

src/main/java/kr/co/teacherforboss/converter/ExamConverter.java, src/main/java/kr/co/teacherforboss/domain/Question.java, src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java, src/main/java/kr/co/teacherforboss/service/examService/ExamQueryService.java, src/main/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/ExamController.java, src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
close #94 
response 예시
```json
{
"isSuccess": true,
"code": "COMMON200",
"message": "성공입니다.",
"result": {
"examRankList": [
{
"rank": 1,
"name": "장은세",
"profileImg": null,
"score": 50,
"mine": false
},
{
"rank": 2,
"name": "백채연",
"profileImg": null,
"score": 40,
"mine": false
},
{
"rank": 3,
"name": "테스트",
"profileImg": null,
"score": 30,
"mine": true
},
{
"rank": 3,
"name": "test",
"profileImg": "https://teacherforboss-bucket.s3.ap-northeast-2.amazonaws.com/profile/Screenshot+2024-02-27+at+9.40.13+PM.png",
"score": 30,
"mine": false
}
]
}
}
```
>
repository에서 orderby 부분을 저대로 둘지, Sort를 파라미터로 받는 방식으로 수정할지 고민입니다!
참고> …
=> ✨[FEAT] 시험 순위 조회 API

src/main/java/kr/co/teacherforboss/converter/ExamConverter.java, src/main/java/kr/co/teacherforboss/service/examService/ExamQueryService.java, src/main/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/ExamController.java, src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
close #119 
- examId에 따라 questionId, solution(해설) 조회
>
=> ✨[FEAT] 문제 해설 리스트 조회 API

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/repository/MemberRepository.java, src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
close #115 
close #110 
일반 로그인의 경우, 로그인시 GENERAL 타입인지 체크해야 한다.
일반 계정으로 회원가입을 하지 않은 회원인 경우, 일반 로그인시 예외처리 (NOT_GENERAL_MEMBER)
>
=> 🐛[FIX] 일반로그인 GENERAL 타입 체크

src/test/java/kr/co/teacherforboss/repository/questionRepository/QuestionRepositoryTest.java, src/test/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImplTest.java, src/test/java/kr/co/teacherforboss/util/AuthTestUtil.java, src/test/java/kr/co/teacherforboss/util/ExamTestUtil.java
close #129 
- 기존 도메인 폴더 구조 및 엔티티 코드 수정에 따라 Test 폴더에서 발생하는 import 에러 및 더미 데이터 구조를 수정했습니다! 
>
=> ❤️‍🩹[FIX] 테스트 코드 오류 수정

src/main/java/kr/co/teacherforboss/repository/ExamRepository.java
close #134 
쿼리문에 memberId, status='ACTIVE' 추가했습니다.
>
=> 🐞[FIX] 시험 치룬 횟수 조회 쿼리 오류 수정

README.md
close #140 
간단하게 기획서 바탕으로 리드미 업데이트했습니다!!
>
=> 📝 [DOCS] 리드미 꾸미기

src/main/java/kr/co/teacherforboss/converter/AuthConverter.java, src/main/java/kr/co/teacherforboss/domain/BusinessAuth.java, src/main/java/kr/co/teacherforboss/domain/common/BaseEntity.java, src/main/java/kr/co/teacherforboss/repository/BusinessAuthRepository.java, src/main/java/kr/co/teacherforboss/service/authService/AuthCommandService.java, src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/AuthController.java, src/main/java/kr/co/teacherforboss/web/dto/AuthResponseDTO.java
close #161 
이미 DB에 등록된 사업자 정보인 경우, 별도의 예외처리 없이 updatedAt 값만 변경하는 로직으로 수정
>
=> ♻️ [REFACTOR] 사업자 정보 인증 API 로직 수정

src/main/java/kr/co/teacherforboss/domain/Answer.java, src/main/java/kr/co/teacherforboss/domain/AnswerLike.java, src/main/java/kr/co/teacherforboss/domain/Category.java, src/main/java/kr/co/teacherforboss/domain/Question.java, src/main/java/kr/co/teacherforboss/domain/QuestionBookmark.java, src/main/java/kr/co/teacherforboss/domain/QuestionHashtag.java, src/main/java/kr/co/teacherforboss/domain/QuestionLike.java
close #167 
엔티티 생성했습니다.
- Category
- Question
- QuestionHashtag
- QuestionLike
- QuestionBookmark
- Answer
- AnswerLike
>
=> ✨[FEAT] 티쳐톡 엔티티 생성

src/main/java/kr/co/teacherforboss/service/s3Service/S3QueryServiceImpl.java
=> ♻️ [REFACTOR] s3 application.yml 변수 path 변경

src/main/java/kr/co/teacherforboss/converter/BoardConverter.java, src/main/java/kr/co/teacherforboss/domain/Question.java, src/main/java/kr/co/teacherforboss/repository/CategoryRepository.java, src/main/java/kr/co/teacherforboss/repository/QuestionHashtagRepository.java, src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java, src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java, src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/BoardController.java, src/main/java/kr/co/teacherforboss/web/dto/BoardRequestDTO.java, src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
=> ✨[FEAT] 티쳐톡 질문 작성 API

src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
close #205 
회원가입 로직 중 누락됐었떤 AuthId 체크 부분 추가했습니당
>
=> ✨[FEAT] 회원가입 API 누락 조건 추가 

src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
close #207 
소셜로그인 400 에러 수정을 위한 코드 수정 작업 진행했습니다
>
=> ❤️‍🩹 [FIX] 소셜로그인 400 에러 수정

src/main/java/kr/co/teacherforboss/converter/BoardConverter.java, src/main/java/kr/co/teacherforboss/repository/PostBookmarkRepository.java, src/main/java/kr/co/teacherforboss/repository/PostLikeRepository.java, src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java
=> ❤️‍🩹[FIX] 보스톡 게시글 좋아요 오류 수정

src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java, src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
반복문 softDelete -> nativeQuery로 벌크 수정
close #178 
반복문 softDelete -> nativeQuery로 벌크 수정
>
=> ❤️‍🩹[FIX] 티쳐톡 삭제 시 답변 삭제 수정

src/main/java/kr/co/teacherforboss/converter/BoardConverter.java, src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java, src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java, src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/BoardController.java, src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
close #번호
티쳐톡 답변 삭제 API 구현했습니다.
req의 questionId 질문글에 달린 답변인지 검증 + 내가 단 답변인지 검증하기 위해
findByIdAndQuestionIdAndMemberIdAndSatatus() 사용했습니다.
>
=> ✨[FEAT] 티쳐톡 답변 삭제 API

src/main/java/kr/co/teacherforboss/config/S3Config.java, src/main/java/kr/co/teacherforboss/converter/BoardConverter.java, src/main/java/kr/co/teacherforboss/domain/enums/ImageOrigin.java, src/main/java/kr/co/teacherforboss/service/s3Service/S3QueryServiceImpl.java, src/main/java/kr/co/teacherforboss/validation/validator/CheckImageOriginValidator.java, src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
close #233
- Post 상세조회 시 imageUrlList 반환 추가
- Question 상세조회 시 imageUrlList 반환 추가
- Answer 리스트 조회 시 imageUrlList 반환 추가
- ImageOrigin enum으로 관리하도록 변경
- S3 region & bucket name static 변수로 수정
>
=> ❤️‍🩹[FIX] res body에 imageUrlList 추가

src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
close #240 
북마크 API 호출시 데이터베이스에 저장된 `bookmarked` 값에 따라 알맞은 boolean값이 리턴되도록 수정했습니다!
>
=> 🐛[FIX] 북마크 API response값 수정 

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/repository/PostRepository.java, src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryService.java, src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
close #219
- 완전히 똑같은 문장/단어를 포함하는 제목이나 본문 검색 기능 구현
- 런칭 이후 ElasticSearch 활용하여 리팩토링 진행
- 검색어 글자수 30자로 제한
- 검색 결과 없는 경우 `POST_NOT_FOUND` 리턴
>
=> ✨[FEAT] 보스톡 키워드 검색 API

src/main/java/kr/co/teacherforboss/converter/BoardConverter.java, src/main/java/kr/co/teacherforboss/repository/CommentRepository.java, src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java, src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/BoardController.java, src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
close #246 
은세 작업한거에서 체리픽했습니다
>
=> ✨[FEAT] 보스톡 댓글 삭제 API

src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java, src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java
=> ❤️‍🩹[FIX] 티쳐톡 질문 리스트 조회 시 카테고리 전체인 경우 추가

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/converter/PaymentConverter.java, src/main/java/kr/co/teacherforboss/repository/TeacherInfoRepository.java, src/main/java/kr/co/teacherforboss/service/paymentService/PaymentQueryService.java, src/main/java/kr/co/teacherforboss/service/paymentService/PaymentQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/util/AES256Util.java, src/main/java/kr/co/teacherforboss/web/controller/PaymentController.java, src/main/java/kr/co/teacherforboss/web/dto/PaymentResponseDTO.java, src/test/java/kr/co/teacherforboss/unit/AES256UtilTest.java
close #251 
티쳐 멤버의 은행, 계좌번호, 예금주명 정보를 반환합니다.
현재 계좌번호 복호화가 되지 않아 우선 pr 올린 뒤 민지님이 해당 부분 체크해주시기로 했습니다!
- 멤버가 티쳐인지 여부 체크
- TeacherInfo에 멤버 정보가 있는지 여부 체크
>
=> ✨[FEAT] 계좌 정보 조회 API 

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/converter/MemberConverter.java, src/main/java/kr/co/teacherforboss/domain/TeacherInfo.java, src/main/java/kr/co/teacherforboss/domain/enums/BooleanType.java, src/main/java/kr/co/teacherforboss/repository/TeacherInfoRepository.java, src/main/java/kr/co/teacherforboss/service/memberService/MemberCommandService.java, src/main/java/kr/co/teacherforboss/service/memberService/MemberCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/MemberController.java, src/main/java/kr/co/teacherforboss/web/dto/MemberRequestDTO.java, src/main/java/kr/co/teacherforboss/web/dto/MemberResponseDTO.java
close #254 
티쳐 리턴값
보스 리턴값
- ROLE값에 따라 API 제작했습니다
- 보스 -> 닉네임, 프로필 이미지 변경 가능
- 티쳐 -> 닉네임, 프로필 이미지 뿐만 아니라 경력, 이메일, 전화번호, 공개 여부 등 변경 가능
- TeacherInfo 엔티티 : 이메일, 전화번호, 각각 공개 여부 필드 추가
>
=> ✨[FEAT] 프로필 수정 API 

src/main/java/kr/co/teacherforboss/converter/AuthConverter.java, src/main/java/kr/co/teacherforboss/domain/Member.java, src/main/java/kr/co/teacherforboss/repository/TeacherInfoRepository.java, src/main/java/kr/co/teacherforboss/service/authService/AuthCommandService.java, src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/AuthController.java, src/main/java/kr/co/teacherforboss/web/controller/MemberController.java, src/main/java/kr/co/teacherforboss/web/dto/AuthResponseDTO.java
close #252 
- 회원 탈퇴 API를 구현했습니다.
>
=> ✨[FEAT] 회원 탈퇴 API

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/domain/Question.java, src/main/java/kr/co/teacherforboss/domain/TeacherSelectInfo.java, src/main/java/kr/co/teacherforboss/repository/TeacherInfoRepository.java, src/main/java/kr/co/teacherforboss/repository/TeacherSelectInfoRepository.java, src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/service/memberService/MemberCommandServiceImpl.java
close #250
* TeacherSelectInfo entity 추가
* 채택 시 티쳐 채택수 증가
* 채택 시 티쳐 포인트 증가
* 회원가입 시 TeacherSelectInfo 생성
>
=> ❤️‍🩹[FIX] 티쳐톡 답변 채택 로직 수정

src/main/java/kr/co/teacherforboss/TeacherforbossApplication.java, src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/apiPayload/exception/handler/HomeHandler.java, src/main/java/kr/co/teacherforboss/config/RedisConfig.java, src/main/java/kr/co/teacherforboss/converter/BoardConverter.java, src/main/java/kr/co/teacherforboss/converter/MemberConverter.java, src/main/java/kr/co/teacherforboss/domain/common/BaseEntity.java, src/main/java/kr/co/teacherforboss/repository/MemberRepository.java, src/main/java/kr/co/teacherforboss/repository/PostRepository.java, src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java, src/main/java/kr/co/teacherforboss/repository/TeacherSelectInfoRepository.java, src/main/java/kr/co/teacherforboss/service/homeService/HomeQueryService.java, src/main/java/kr/co/teacherforboss/service/homeService/HomeQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/HomeController.java, src/main/java/kr/co/teacherforboss/web/dto/HomeResponseDTO.java
close #239
- 레디스 캐시 설정
- 보스톡 인기 게시글 조회 API
- 티쳐톡 인기 게시글 조회 API
- 이번주 인기 티쳐 조회 API
>
*** 인기 계산할 때 일주일 필터링 걸어서 계산하는 거 아직 추가 안함 !!!!!!!!!!!!!!!! 해야됨 ***
=> ✨[FEAT] 홈 뷰 인기 컨텐츠 조회 API

src/main/java/kr/co/teacherforboss/converter/MemberConverter.java, src/main/java/kr/co/teacherforboss/web/controller/MemberController.java, src/main/java/kr/co/teacherforboss/web/dto/MemberResponseDTO.java
=> ✨[FEAT] 계정 정보 조회 API

src/main/java/kr/co/teacherforboss/converter/BoardConverter.java, src/main/java/kr/co/teacherforboss/converter/MemberConverter.java, src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java, src/main/java/kr/co/teacherforboss/service/mypageService/MypageQueryService.java, src/main/java/kr/co/teacherforboss/service/mypageService/MypageQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/MypageController.java, src/main/java/kr/co/teacherforboss/web/dto/MypageResponseDTO.java
close #260 
- 사용자가 최근 답변한 질문글이 최상단에 오도록 정렬해야 하기에 where절 및 order by 에 answer created_at 기준으로 비교하며 정렬하는 조건 추가
- 무한 스크롤 적용
>
쿼리 괜찮나요............?
=> ✨[FEAT] 내가 답변한 질문글 조회 API

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/converter/PaymentConverter.java, src/main/java/kr/co/teacherforboss/domain/TeacherInfo.java, src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandService.java, src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/PaymentController.java, src/main/java/kr/co/teacherforboss/web/dto/MemberRequestDTO.java, src/main/java/kr/co/teacherforboss/web/dto/PaymentRequestDTO.java, src/main/java/kr/co/teacherforboss/web/dto/PaymentResponseDTO.java
close #268 
- 계좌번호, 은행, 예금주명 입력시 정보 업데이트
- 모든 필드 미입력시 에러 반환
- TeacherInfo 엔티티 emailOpen, phoneOpen 필드 조건 추가
>
=> ✨[FEAT] 계좌 변경 API

src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java, src/main/java/kr/co/teacherforboss/converter/PaymentConverter.java, src/main/java/kr/co/teacherforboss/domain/Exchange.java, src/main/java/kr/co/teacherforboss/repository/ExchangeRepository.java, src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandService.java, src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/PaymentController.java, src/main/java/kr/co/teacherforboss/web/dto/PaymentResponseDTO.java
close #279 
- 관리자 계정으로만 API 사용 가능
- 테스트 관리자 계정은 API 명세서 댓글로 작성
**티포 환전 완료 처리 API만 봐주시면 됩니다! (다른 브랜치에서 머지함)**
- 관리자 외 Role 계정일시 예외 처리
- 이미 처리 완료된 내역일시 에외 처리
- 
>
메서드명 괜찮은지 봐주세요.................!!
=> ✨[FEAT] 티포 환전 완료 처리 API

src/main/java/kr/co/teacherforboss/converter/PaymentConverter.java, src/main/java/kr/co/teacherforboss/service/paymentService/PaymentQueryService.java, src/main/java/kr/co/teacherforboss/service/paymentService/PaymentQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/PaymentController.java, src/main/java/kr/co/teacherforboss/web/dto/PaymentResponseDTO.java
close #291 
현재 포유한 티포 조회 (TeacherSelectInfo의 points)
>
=> :sparkles: [FEAT] 현재 보유 티포 조회 API

src/main/java/kr/co/teacherforboss/converter/BoardConverter.java, src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java, src/main/java/kr/co/teacherforboss/service/mypageService/MypageQueryService.java, src/main/java/kr/co/teacherforboss/service/mypageService/MypageQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/MypageController.java, src/main/java/kr/co/teacherforboss/web/dto/MypageResponseDTO.java
=> ✨ [FEAT] 내가 작성한 질문글 API

src/main/java/kr/co/teacherforboss/converter/BoardConverter.java, src/main/java/kr/co/teacherforboss/repository/PostRepository.java, src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java, src/main/java/kr/co/teacherforboss/service/mypageService/MypageQueryService.java, src/main/java/kr/co/teacherforboss/service/mypageService/MypageQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/MypageController.java, src/main/java/kr/co/teacherforboss/web/dto/MypageResponseDTO.java
=> ✨[FEAT] 내가 작성한 게시글 조회

src/main/java/kr/co/teacherforboss/converter/BoardConverter.java, src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java, src/main/java/kr/co/teacherforboss/service/mypageService/MypageQueryService.java, src/main/java/kr/co/teacherforboss/service/mypageService/MypageQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/MypageController.java
=> ✨[FEAT] 내가 저장한 질문 조회

src/main/java/kr/co/teacherforboss/converter/MemberConverter.java, src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java, src/main/java/kr/co/teacherforboss/service/memberService/MemberQueryService.java, src/main/java/kr/co/teacherforboss/service/memberService/MemberQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/MemberController.java, src/main/java/kr/co/teacherforboss/web/dto/MemberResponseDTO.java
close #271 
티처 최근 답변 조회 기능을 구현했습니다.
>
=> ✨[FEAT] 티쳐 최근 답변 조회

src/main/java/kr/co/teacherforboss/converter/BoardConverter.java, src/main/java/kr/co/teacherforboss/domain/QuestionTicket.java, src/main/java/kr/co/teacherforboss/domain/enums/HistoryType.java, src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java, src/main/java/kr/co/teacherforboss/repository/CommentRepository.java, src/main/java/kr/co/teacherforboss/repository/PostBookmarkRepository.java, src/main/java/kr/co/teacherforboss/repository/QuestionBookmarkRepository.java, src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java, src/main/java/kr/co/teacherforboss/repository/QuestionTicketRepository.java, src/main/java/kr/co/teacherforboss/repository/TeacherSelectInfoRepository.java, src/main/java/kr/co/teacherforboss/service/mypageService/MypageQueryService.java, src/main/java/kr/co/teacherforboss/service/mypageService/MypageQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/MypageController.java, src/main/java/kr/co/teacherforboss/web/dto/MypageResponseDTO.java
티쳐/보스에 따라 조회되야하는 정보가 다른데, 변수명을 어떻게 할지 결정 필요
close #296 
repository에서 조회만 해오면 되도록 초안 작성
USER ROLE이 티쳐냐 보스냐에 따라서 조회되는 정보가 다른데, response 변수명을 통일하는건 어떨지?
남긴 답변/댓글 이니까 history로 해도 좋고, 아니면 point / questionTicketCount 처럼 하나는 null로 보내는 방법?
=> ✨[FEAT] 보라색 칩 정보 조회

src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
close #번호
teacherInfo Map Key 조회값 변경
>
=> 🐛[FIX] 티쳐톡 Answer 티쳐의 role, level 누락 해결

src/main/java/kr/co/teacherforboss/web/dto/MemberRequestDTO.java
=> ❤️‍🩹[FIX] 티처 프로필 수정 API - 이메일 null 허용

src/main/java/kr/co/teacherforboss/converter/NotificationConverter.java, src/main/java/kr/co/teacherforboss/domain/AgreementTerm.java, src/main/java/kr/co/teacherforboss/domain/NotificationSetting.java, src/main/java/kr/co/teacherforboss/repository/NotificationSettingRepository.java, src/main/java/kr/co/teacherforboss/service/notificationService/NotificationCommandService.java, src/main/java/kr/co/teacherforboss/service/notificationService/NotificationCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/service/notificationService/NotificationQueryService.java, src/main/java/kr/co/teacherforboss/service/notificationService/NotificationQueryServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/NotificationController.java, src/main/java/kr/co/teacherforboss/web/dto/NotificationRequestDTO.java, src/main/java/kr/co/teacherforboss/web/dto/NotificationResponseDTO.java
=> ✨[FEAT] 푸시알림 설정 api

src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
=> ✨[FEAT] 회원가입 시 사업자 인증 로직 주석 처리 

src/main/java/kr/co/teacherforboss/aop/AwsSnsAspect.java, src/main/java/kr/co/teacherforboss/aop/NotificationAspect.java, src/main/java/kr/co/teacherforboss/domain/DeviceToken.java, src/main/java/kr/co/teacherforboss/repository/NotificationRepository.java, src/main/java/kr/co/teacherforboss/service/notificationService/NotificationCommandService.java, src/main/java/kr/co/teacherforboss/service/notificationService/NotificationCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/service/snsService/SnsServiceImpl.java, src/main/java/kr/co/teacherforboss/web/controller/SnsController.java, src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
* 회원가입 / 로그인 시 deviceToken 저장, sns endpoint 등록하는 부분
* 테스트를 위한 api 추가
close #293
>
=> ❤️‍🩹[FIX] sns endpoint 및 deviceToken 관리 로직 수정

src/main/java/kr/co/teacherforboss/config/AsyncConfig.java, src/main/java/kr/co/teacherforboss/domain/vo/mailVO/ExchangeMail.java, src/main/java/kr/co/teacherforboss/service/mailService/MailCommandService.java, src/main/java/kr/co/teacherforboss/service/mailService/MailCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/dto/PaymentRequestDTO.java, src/main/resources/templates/exchange.html
=> ✨[FEAT] 환전 신청 API 수정 (리뷰 반영)

src/main/java/kr/co/teacherforboss/config/AsyncConfig.java, src/main/java/kr/co/teacherforboss/domain/vo/mailVO/ExchangeMail.java, src/main/java/kr/co/teacherforboss/service/mailService/MailCommandService.java, src/main/java/kr/co/teacherforboss/service/mailService/MailCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandServiceImpl.java, src/main/java/kr/co/teacherforboss/web/dto/PaymentRequestDTO.java, src/main/resources/templates/exchange.html
close #310 
- 1TP당 1000원, 10TP부터 환전 가능하며, 환전 수수료 없는 것으로 로직 수정
- 메일 전송 비동기 처리 위해 AysncConfig 파일 추가 및 @Async 추가 
>
=> ✨[FEAT] 환전 신청 API 수정

src/main/java/kr/co/teacherforboss/domain/TeacherInfo.java, src/main/java/kr/co/teacherforboss/domain/vo/mailVO/TeacherAuditMail.java, src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
close #324 
사업자 관련 정보 API 주석처리
>
=> ✨[FEAT] 사업자 정보 관련 정보 주석처리
